version: "3.8"
services:

  emongo:
    image: mongo:4
    container_name: emongo
    environment:
      - MONGO_INITDB_DATABASE=epoc
    ports:
      - "27017:27017"

  emartdb:
    image: mysql:8.0.33
    container_name: emartdb
    environment:
      - MYSQL_ROOT_PASSWORD=emartdbpass
      - MYSQL_DATABASE=books
    ports:
      - "3306:3306"

  webapi:
    build:
      context: ./javaapi
    ports:
      - "9000:9000"
    restart: always
    container_name: webapi
    depends_on: 
      - emartdb


  api:
    build:
      context: ./nodeapi
    ports:
      - "5000:5000"
    container_name: api
    restart: always
    depends_on:
      - nginx
      - emongo


      
  client:
    build:
      context: ./client
    ports:
      - "4200:4200"
    container_name: client
    depends_on:
      - api
      - webapi





  nginx:
    build:
      context: ./nginx
    restart: always
    container_name: nginx
    ports:
      - "80:80"

